### ISSUE TITLE
R_internal.numMetaCols is not in sync with number of meta data columns

### ISSUE THREAD

**Issue by IvoryC** [IvoryC/sheepdog_testing_suite#64]

**Comment by IvoryC** [comment]
R_internal.numMetaCols

See pipeline /scratch/afodor_research/blj_pipeline/ieclabau/MockMainTest_2019Jun28/testHN2_2019Jun28

stack trace:

FATAL APPLICATION ERROR  -->
 Program args: -b /scratch/afodor_research/ieclabau/publicGit/sheepdog_testing_suite/MockMain/pipelines -u ~ -c /scratch/afodor_research/ieclabau/publicGit/blj_support/resources/test/config/hpc/testHN2.properties
biolockj.exception.ConfigFormatException: [ R_internal.numMetaCols=-1 ] 
Current value "-1" does not meet format requirements!
Property only accepts positive integer values
Restart pipeline after updating the property value in: /scratch/afodor_research/ieclabau/publicGit/blj_support/resources/test/config/hpc/testHN2.properties
RESTART SHORTCUT CMD ---> "blj_rerun /scratch/afodor_research/ieclabau/publicGit/blj_support/resources/test/config/hpc/testHN2.properties"
	at biolockj.Config.getPositiveInteger(Config.java:268)
	at biolockj.util.RMetaUtil.updateRConfig(RMetaUtil.java:224)
	at biolockj.util.RMetaUtil.classifyReportableMetadata(RMetaUtil.java:183)
	at biolockj.Pipeline.refreshRCacheIfNeeded(Pipeline.java:288)
	at biolockj.Pipeline.executeModule(Pipeline.java:42)
	at biolockj.Pipeline.executeModules(Pipeline.java:185)
	at biolockj.Pipeline.runPipeline(Pipeline.java:132)
	at biolockj.BioLockJ.runPipeline(BioLockJ.java:267)
	at sheepdog.MockMain.main(Unknown Source)
